# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example
description = "Base16 is a simple and colorful theme with the base16 eighties colorscheme"
features = ["blog", "syntax highlighting"]
homepage = "https://htdvisser.github.io/hugo-base16-theme/"
license = "MIT"
licenselink = "http://htdvisser.mit-license.org/"
min_version = 0.14
name = "Base16"
tags = ["blog", "syntax highlighting"]

[original]
homepage = "https://github.com/htdvisser"
name = "Hylke Visser"
